name: Build Go application
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Download dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o app main.go

      - name: Run tests
        run: go test -v

      - name: verify the build
        run: ls -la app
