name: Build Go application
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Download dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o app main.go

      - name: Run tests
        run: go test -v

      - name: verify the build
        run: ls -la app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload binary to S3
        run: |
          aws s3 cp app s3://video-platform-deployments-zoaewe3s/app-${{ github.sha }}
          echo "Binary uploaded to S3 with commit hash: ${{ github.sha }}"
